Repository PCL-Community/PCL.Neo, pull requests merged in 2025-05, with the labels that each got.

#78 feat: 添加导航功能和返回按钮支持，更新语言资源
  PCL.Neo/Assets/Language/en-US.axaml
  PCL.Neo/Assets/Language/zh-CN.axaml
  PCL.Neo/Services/NavigationService.cs
  PCL.Neo/ViewModels/MainWindowViewModel.cs
  PCL.Neo/Views/MainWindow.axaml
  PCL.Neo/Views/MainWindow.axaml.cs
Labels: enhancement

#82 feat: 重构服务注册，添加多个视图模型和日志管理功能，用户功能等多个核心功能，更新导航服务以支持异步操作
  PCL.Neo.Core/Models/Minecraft/Game/Data/Arguments.cs
  PCL.Neo.Core/Models/Minecraft/Game/Data/AssetIndex.cs
  PCL.Neo.Core/Models/Minecraft/Game/Data/GameEntity.cs
  PCL.Neo.Core/Models/Minecraft/Game/Data/LaunchOptionsData.cs
  PCL.Neo.Core/Models/Minecraft/Game/Data/Rule.cs
  PCL.Neo.Core/Models/Minecraft/Game/Data/VersionInfo.cs
  PCL.Neo.Core/Models/Minecraft/Game/GameLauncher.cs
  PCL.Neo.Core/Models/Minecraft/Game/GameService.cs
  PCL.Neo.Core/Models/Minecraft/Game/LaunchOptions.cs
  PCL.Neo.Core/Models/Minecraft/Game/Versions.cs
  PCL.Neo.Core/Models/Minecraft/Java/IJavaManager.cs
  PCL.Neo.Core/Models/Minecraft/Java/JavaData.cs
  PCL.Neo.Core/Models/Minecraft/Java/JavaManager.cs
  PCL.Neo.Core/PCL.Neo.Core.csproj
  PCL.Neo/Animations/AnimationExtensions.cs
  PCL.Neo/Animations/Easings/EasingType.cs
  PCL.Neo/Animations/MarginAnimation.cs
  PCL.Neo/App.axaml
  PCL.Neo/App.axaml.cs
  PCL.Neo/Attributes.cs
  PCL.Neo/Helpers/AnimationHelper.cs
  PCL.Neo/Models/Minecraft/Game/Log.cs
  PCL.Neo/Models/User/OfflineUser.cs
  PCL.Neo/Models/User/UserInfo.cs
  PCL.Neo/PCL.Neo.csproj
  PCL.Neo/Program.cs
  PCL.Neo/Services/INavigationService.cs
  PCL.Neo/Services/NavigationService.cs
  PCL.Neo/Services/StorageService.cs
  PCL.Neo/Services/UserService.cs
  PCL.Neo/Utils/BoolToOnlineStatusConverter.cs
  PCL.Neo/ViewModels/Attributes.cs
  PCL.Neo/ViewModels/DownloadViewModel.cs
  PCL.Neo/ViewModels/Home/GameSettingsViewModel.cs
  PCL.Neo/ViewModels/Home/HomeSubViewModel.cs
  PCL.Neo/ViewModels/Home/HomeViewModel.cs
  PCL.Neo/ViewModels/Home/VersionManagerViewModel.cs
  PCL.Neo/ViewModels/HomeViewModel.cs
  PCL.Neo/ViewModels/LogViewModel.cs
  PCL.Neo/ViewModels/MainWindowViewModel.cs
  PCL.Neo/Views/Home/ExportView.axaml
  PCL.Neo/Views/Home/ExportView.axaml.cs
  PCL.Neo/Views/Home/GameSettingsView.axaml
  PCL.Neo/Views/Home/GameSettingsView.axaml.cs
  PCL.Neo/Views/Home/ModifyView.axaml
  PCL.Neo/Views/Home/ModifyView.axaml.cs
  PCL.Neo/Views/Home/OverviewView.axaml
  PCL.Neo/Views/Home/OverviewView.axaml.cs
  PCL.Neo/Views/Home/SavesView.axaml
  PCL.Neo/Views/Home/SavesView.axaml.cs
  PCL.Neo/Views/Home/SettingsView.axaml
  PCL.Neo/Views/Home/SettingsView.axaml.cs
  PCL.Neo/Views/Home/VersionManagerView.axaml
  PCL.Neo/Views/Home/VersionManagerView.axaml.cs
  PCL.Neo/Views/HomeView.axaml
  PCL.Neo/Views/LogView.axaml
  PCL.Neo/Views/LogView.axaml.cs
  PCL.Neo/Views/MainWindow.axaml
Labels: enhancement, 重大更改

#83 optimize: 优雅！优雅！还是tmd优雅！
  PCL.Neo.Core/FileExtension.cs
  PCL.Neo.Core/Models/DownloadService.cs
  PCL.Neo.Core/Models/Minecraft/Game/Data/Arguments.cs
  PCL.Neo.Core/Models/Minecraft/Game/Data/GameEntity.cs
  PCL.Neo.Core/Models/Minecraft/Game/Data/Rule.cs
  PCL.Neo.Core/Models/Minecraft/Game/Data/VersionInfo.cs
  PCL.Neo.Core/Models/Minecraft/Game/GameLauncher.cs
  PCL.Neo.Core/Models/Minecraft/Game/GameService.cs
  PCL.Neo.Core/Models/Minecraft/Game/Versions.cs
  PCL.Neo.Core/Models/Minecraft/Java/IJavaManager.cs
  PCL.Neo.Core/Models/Minecraft/Java/JavaData.cs
  PCL.Neo.Core/Models/Minecraft/Java/JavaFetcherOnline.cs
  PCL.Neo.Core/Models/Minecraft/Java/JavaManager.cs
  PCL.Neo.Core/Models/Minecraft/Java/JavaVersionMatcherForGameEntityExtension.cs
  PCL.Neo.Core/Models/Minecraft/Java/Unix.cs
  PCL.Neo.Core/PCL.Neo.Core.csproj
  PCL.Neo.Core/Utils/ExeArchitectureUtils.cs
  PCL.Neo.Core/Utils/SystemUtils.cs
  PCL.Neo.Tests/Core/Models/FileHelper/FileTest.cs
  PCL.Neo.Tests/Core/Models/Minecraft/JavaTest.cs
  PCL.Neo/App.axaml
  PCL.Neo/App.axaml.cs
  PCL.Neo/PCL.Neo.csproj
  PCL.Neo/Services/NavigationService.cs
  PCL.Neo/Services/StorageService.cs
  PCL.Neo/Services/UserService.cs
  PCL.Neo/ViewModels/Home/GameSettingsViewModel.cs
  PCL.Neo/ViewModels/Home/HomeSubViewModel.cs
  PCL.Neo/ViewModels/Home/HomeViewModelBackup.cs
  PCL.Neo/ViewModels/Home/VersionManagerViewModel.cs
  PCL.Neo/ViewModels/MainWindowViewModel.cs
  PCL.Neo/ViewModels/Setup/SetupLaunchViewModel.cs
  PCL.Neo/ViewModels/SetupViewModel.cs
  PCL.Neo/Views/Home/HomeSubView.axaml
  PCL.Neo/Views/MainWindow.axaml
  PCL.Neo/Views/Setup/SetupLaunchView.axaml
  PCL.Neo/Views/Setup/SetupLaunchView.axaml.cs
  PCL.Neo/Views/Setup/SetupOtherView.axaml
  PCL.Neo/Views/Setup/SetupOtherView.axaml.cs
  PCL.Neo/Views/Setup/SetupStyleView.axaml
  PCL.Neo/Views/Setup/SetupStyleView.axaml.cs
  PCL.Neo/Views/SetupView.axaml
  PCL.Neo/Views/SetupView.axaml.cs
Labels: 新功能, 重大更改, 优化

#88 删除离线用户类，重构用户信息类以使用基础账户，更新用户服务以支持新账户结构
  PCL.Neo.Core/Models/Profile/GameProfile.cs
  PCL.Neo.Core/Service/Accounts/AccountService.cs
  PCL.Neo.Core/Service/Accounts/AccountServiceExtensions.cs
  PCL.Neo.Core/Service/Accounts/Exceptions/YggdrasilAuthException.cs
  PCL.Neo.Core/Service/Accounts/IAccountService.cs
  PCL.Neo.Core/Service/Accounts/ILoggingExtensions.cs
  PCL.Neo.Core/Service/Accounts/IYggdrasilAuth/IYggdrasilAuthService.cs
  PCL.Neo.Core/Service/Accounts/IYggdrasilAuth/YggdrasilAuthService.cs
  PCL.Neo.Core/Service/Accounts/OAuthService/AuthCodeMode.cs
  PCL.Neo.Core/Service/Accounts/OAuthService/OAuthData.cs
  PCL.Neo.Core/Service/Accounts/OAuthService/RedirectServer/AuthCode.cs
  PCL.Neo.Core/Service/Accounts/OAuthService/RedirectServer/RedirectServer.cs
  PCL.Neo.Core/Service/Accounts/Storage/BaseAccount.cs
  PCL.Neo.Core/Service/Accounts/Storage/MsaAccount.cs
  PCL.Neo.Core/Service/Accounts/Storage/OfflineAccount.cs
  PCL.Neo.Core/Service/Accounts/Storage/YggdrasilAccount.cs
  PCL.Neo.Core/Service/Profiles/IProfileService.cs
  PCL.Neo.Core/Service/Profiles/ProfileService.cs
  PCL.Neo.Tests/Core/Service/Accounts/Storage/BaseAccountTest.cs
  PCL.Neo.Tests/SaveUserInfoTest.cs
  PCL.Neo/Models/User/OfflineUser.cs
  PCL.Neo/Models/User/UserInfo.cs
  PCL.Neo/Services/UserService.cs
  PCL.Neo/ViewModels/Home/HomeSubViewModel.cs
Labels: 新功能, 优化

#93 DELETE 删除MyTitleBar & FEAT 添加Yggdrasil（半成品）
  .editorconfig
  PCL.Neo.Core/Service/Accounts/AccountService.cs
  PCL.Neo.Core/Service/Accounts/IYggdrasilAuth/Data/YggdrasilAgent.cs
  PCL.Neo.Core/Service/Accounts/IYggdrasilAuth/Data/YggdrasilAuthRequest.cs
  PCL.Neo.Core/Service/Accounts/IYggdrasilAuth/Data/YggdrasilAuthResponse.cs
  PCL.Neo.Core/Service/Accounts/IYggdrasilAuth/Data/YggdrasilErrorResponse.cs
  PCL.Neo.Core/Service/Accounts/IYggdrasilAuth/Data/YggdrasilProfile.cs
  PCL.Neo.Core/Service/Accounts/IYggdrasilAuth/Data/YggdrasilProperty.cs
  PCL.Neo.Core/Service/Accounts/IYggdrasilAuth/Data/YggdrasilRefreshRequest.cs
  PCL.Neo.Core/Service/Accounts/IYggdrasilAuth/Data/YggdrasilUser.cs
  PCL.Neo.Core/Service/Accounts/IYggdrasilAuth/IYggdrasilAuthService.cs
  PCL.Neo.Core/Service/Accounts/IYggdrasilAuth/YggdrasilAuthService.cs
  PCL.Neo.Core/Service/Accounts/MicrosoftAuth/DeviceCodeData.cs
  PCL.Neo.Core/Service/Accounts/MicrosoftAuth/IMicrosoftAuthService.cs
  PCL.Neo.Core/Service/Accounts/MicrosoftAuth/MicrosoftAuthService.cs
  PCL.Neo.Core/Service/Accounts/OAuthService/AuthCodeMode.cs
  PCL.Neo.Core/Service/Accounts/OAuthService/MinecraftInfo.cs
  PCL.Neo.Core/Service/Accounts/OAuthService/NotHaveGameException.cs
  PCL.Neo.Core/Service/Accounts/OAuthService/OAuth.cs
  PCL.Neo.Core/Service/Accounts/OAuthService/OAuthData.cs
  PCL.Neo.Core/Service/Accounts/OAuthService/RedirectServer/RedirectAuthCode.cs
  PCL.Neo.Core/Utils/Net.cs
  PCL.Neo.Tests/Core/Service/Accounts/Storage/BaseAccountTest.cs
  PCL.Neo.Tests/SaveUserInfoTest.cs
  PCL.Neo/Controls/MyTitleBar.axaml
  PCL.Neo/Controls/MyTitleBar.axaml.cs
  PCL.Neo/Models/User/UserInfo.cs
  PCL.Neo/Services/UserService.cs
  PCL.Neo/ViewModels/HomeViewModel.cs
  PCL.Neo/Views/HomeView.axaml
Labels: 新功能

#109 fix: `HomeView` not showing
  .github/workflows/build.yml
  PCL.Neo/App.axaml.cs
  PCL.Neo/PCL.Neo.csproj
  PCL.Neo/PCL.Neo.pupnet.conf
Labels: Bug

#94 feat: Downloader
  PCL.Neo.Core/Download/DownloadReceipt.cs
  PCL.Neo.Core/Download/Downloader.cs
  PCL.Neo.Core/Download/FileIntegrity.cs
  PCL.Neo.Core/Models/DownloadService.cs
  PCL.Neo.Core/Models/Minecraft/Game/GameService.cs
  PCL.Neo.Core/Models/Minecraft/Game/Versions.cs
  PCL.Neo.Core/Models/Minecraft/Java/JavaFetcherOnline.cs
  PCL.Neo.Core/PCL.Neo.Core.csproj
  PCL.Neo.Core/Service/Accounts/IYggdrasilAuth/YggdrasilAuthService.cs
  PCL.Neo.Core/Shared.cs
  PCL.Neo.Core/Utils/Net.cs
  PCL.Neo.Core/Utils/StreamExt.cs
  PCL.Neo.Core/Utils/SynchronousProgress.cs
  PCL.Neo.Tests/Core/Download/DownloadTest.cs
  PCL.Neo.Tests/Core/Models/FileHelper/FileTest.cs
  PCL.Neo.Tests/Core/Models/Minecraft/JavaTest.cs
  PCL.Neo.Tests/PCL.Neo.Tests.csproj
  PCL.Neo/App.axaml.cs
  PCL.Neo/PCL.Neo.csproj
Labels: 新功能

#85 feat: JobService
  PCL.Neo.Tests/Services/JobServiceTest.cs
  PCL.Neo/App.axaml.cs
  PCL.Neo/Converters/DoublePercentageConverter.cs
  PCL.Neo/Jobs/TestJob1.cs
  PCL.Neo/Services/JobService.cs
  PCL.Neo/ViewModels/Home/HomeSubViewModel.cs
  PCL.Neo/ViewModels/Job/JobSubViewModel.cs
  PCL.Neo/ViewModels/JobViewModel.cs
  PCL.Neo/ViewModels/MainWindowViewModel.cs
  PCL.Neo/Views/Home/HomeSubView.axaml
  PCL.Neo/Views/Job/JobSubView.axaml
  PCL.Neo/Views/Job/JobSubView.axaml.cs
  PCL.Neo/Views/JobView.axaml
  PCL.Neo/Views/JobView.axaml.cs
Labels: 新功能

#122 feat: 完成跨平台音频播放模块
  PCL.Neo.Core/PCL.Neo.Core.csproj
  PCL.Neo.Core/Service/Audio/AudioDemo.cs
  PCL.Neo.Core/Service/Audio/AudioOptions.cs
  PCL.Neo.Core/Service/Audio/AudioPlayerExtensions.cs
  PCL.Neo.Core/Service/Audio/AudioService.cs
  PCL.Neo.Core/Service/Audio/AudioServiceFactory.cs
  PCL.Neo.Core/Service/Audio/IAudioService.cs
  PCL.Neo.Core/Service/Audio/LinuxAudioService.cs
  PCL.Neo.Core/Service/Audio/MacOsAudioService.cs
  PCL.Neo.Core/Service/Audio/README.md
  PCL.Neo.Core/Service/Audio/WindowsAudioService.cs
Labels: 新功能
